<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="2.0"
    xmlns:html="http://www.w3.org/TR/REC-html40"
    xmlns:image="http://www.google.com/schemas/sitemap-image/1.1"
    xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9"
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
    <xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes"/>
    <xsl:template match="/">
        <html xmlns="http://www.w3.org/1999/xhtml">
        <head>
            <title>XML Sitemap</title>
            <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
            <style type="text/css">
                body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen-Sans, Ubuntu, Cantarell, "Helvetica Neue", sans-serif; color: #444; margin: 0; padding: 20px; font-size: 13px; }
                #content { max-width: 960px; margin: 0 auto; }
                h1 { color: #333; font-size: 24px; font-weight: bold; margin-bottom: 10px; }
                p { margin-top: 0; line-height: 1.5; color: #555; }
                a { color: #2563eb; text-decoration: none; }
                a:hover { text-decoration: underline; }
                .pena-brand { color: #d63638; font-weight: bold; }
                table { width: 100%; border-collapse: collapse; margin-top: 15px; font-size: 13px; }
                /* PERUBAHAN PADDING DI SINI: Dibuat lebih rapat (4px atas-bawah) */
                th { text-align: left; padding: 4px 10px; border-bottom: 2px solid #ddd; font-weight: bold; color: #333; }
                td { padding: 4px 10px; border-bottom: 1px solid #eee; }
                tr:nth-child(even) td { background-color: #f9f9f9; }
                td a { color: #333; }
                td a:hover { color: #2563eb; }
            </style>
        </head>
        <body>
            <div id="content">
                <h1>XML Sitemap</h1>
                <p>Generated by <span class="pena-brand">Pena SEO</span>, this is an XML Sitemap, meant for consumption by search engines.</p>
                <p>You can find more information about XML sitemaps on <a href="http://sitemaps.org" class="pena-brand">sitemaps.org</a>.</p>
                
                <xsl:choose>
                    <!-- TAMPILAN UNTUK SITEMAP INDEX (Sitemap Utama) -->
                    <xsl:when test="sitemap:sitemapindex">
                        <p>This XML Sitemap Index file contains <xsl:value-of select="count(sitemap:sitemapindex/sitemap:sitemap)"/> sitemaps.</p>
                        <table>
                            <thead>
                                <tr>
                                    <th>Sitemap</th>
                                    <th>Last Modified</th>
                                </tr>
                            </thead>
                            <tbody>
                                <xsl:for-each select="sitemap:sitemapindex/sitemap:sitemap">
                                    <tr>
                                        <td><a href="{sitemap:loc}"><xsl:value-of select="sitemap:loc"/></a></td>
                                        <td><xsl:value-of select="sitemap:lastmod"/></td>
                                    </tr>
                                </xsl:for-each>
                            </tbody>
                        </table>
                    </xsl:when>
                    
                    <!-- TAMPILAN UNTUK URL SET (Post, Page, Category) -->
                    <xsl:when test="sitemap:urlset">
                        <p>This XML Sitemap contains <xsl:value-of select="count(sitemap:urlset/sitemap:url)"/> URLs.</p>
                        <table>
                            <thead>
                                <tr>
                                    <th>URL</th>
                                    <th>Last Modified</th>
                                    <th>Change Freq</th>
                                    <th>Priority</th>
                                </tr>
                            </thead>
                            <tbody>
                                <xsl:for-each select="sitemap:urlset/sitemap:url">
                                    <tr>
                                        <td><a href="{sitemap:loc}"><xsl:value-of select="sitemap:loc"/></a></td>
                                        <td><xsl:value-of select="sitemap:lastmod"/></td>
                                        <td><xsl:value-of select="sitemap:changefreq"/></td>
                                        <td><xsl:value-of select="sitemap:priority"/></td>
                                    </tr>
                                </xsl:for-each>
                            </tbody>
                        </table>
                    </xsl:when>
                </xsl:choose>
            </div>
        </body>
        </html>
    </xsl:template>
</xsl:stylesheet>